spring:
  datasource:
    url: jdbc:h2:file:./db/social-auth
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true

  social:
    encrypt:
      key: key
      salt: salt
    facebook:
      clientId:
      clientSecret:
    vk:
      clientId:
      clientSecret:
    yandex:
      appId:
      appSecret:
